spring.application.name=nutrition-analysis-service

server.port=8083

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=nutrition-analysis

spring.rabbitmq.addresses=amqps://oiwxznpp:MDxobgtu6hEoEHOIOerfMPhiGFaRPKNx@beaver.rmq.cloudamqp.com/oiwxznpp

broker.queue.feeds.name=default.feeds

feed.cost.service.url=http://localhost:8082

