spring.application.name=feed-management-service

server.port=8081

spring.datasource.url= jdbc:postgresql://localhost:5432/feed-management
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://oiwxznpp:MDxobgtu6hEoEHOIOerfMPhiGFaRPKNx@beaver.rmq.cloudamqp.com/oiwxznpp

broker.queue.feeds.name=default.feeds