spring.application.name=feed-cost-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/feed-cost
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true